### ISSUE TITLE
[Question] More easily accessible documentation available ?

### ISSUE THREAD

**Issue by cwdjankoski** [criteo/criteo-api-python-sdk#17]
Hello Criteo Team, thank you for making python client libraries available to communicate to your Marketing API.
We have 2 questions, hope you can help us with them:
  -  is there some more "easily accessible" documentation available. we tried to search [here](https://github.com/criteo/criteo-api-python-sdk/tree/main/sdks/marketingsolutions_2024-01#documentation-for-models) but these are a bit too dry / technical for our level. we were wondering if you have somewhere an example script that:
    -  connects to the criteo marketing api with user/pass
    - fetches lists of advertiser ids
    - creates a new audience for one advertiser
    - updates an old audience for another advertiser
Something that would resemble more "real-life" situations that teams from your clients might face.

  - Could you please share with us if you plan to develop and maintain these python libraries. in the past we used to use another criteo client python library which was discontinued / stopped working, so we had to roll our own for a while. now that they are back we were wondering if we should switch back to using these.

Thank you in front for any thoughts and comments. Greetings.

**Comment by gturri** [comment]
hi @cwdjankoski ,
There is more doc here https://developers.criteo.com/marketing-solutions . (In particular, for the connection part, there is this https://developers.criteo.com/marketing-solutions/docs/oauth-implementation ).
There are also some example in this repo:
* here one which uses client credentials: https://github.com/criteo/criteo-api-python-sdk/blob/main/sdks/marketingsolutions_2024-01/test/example_application_with_client_credentials.py
* here on which uses auth code: https://github.com/criteo/criteo-api-python-sdk/blob/main/sdks/marketingsolutions_2024-01/test/example_application_with_auth_code.py

I hope that it answers your question about the doc. Feel free to reopen this issue if it does not.

---
About the plan to maintain these libraries: the short answer is "yes".

In particular, since these libs are autogenerated, they require little maintenance, so it's likely we'll continue to provide them.
